### ISSUE TITLE
Supports `df.drop("a")`

### ISSUE THREAD

**Issue by wenleix** [pytorch/torcharrow#404]
Pandas's drop doesn't directly support it (and has to do `df.drop(["a", "b"])`:

```python
>>> import pandas as pd
>>> df = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})
>>> df.drop("a")
  File "<stdin>", line 1, in <module>
  File "/Users/wxie/opt/miniconda3/lib/python3.9/site-packages/pandas-1.3.4-py3.9-macosx-10.9-x86_64.egg/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/Users/wxie/opt/miniconda3/lib/python3.9/site-packages/pandas-1.3.4-py3.9-macosx-10.9-x86_64.egg/pandas/core/frame.py", line 4906, in drop
    return super().drop(
  File "/Users/wxie/opt/miniconda3/lib/python3.9/site-packages/pandas-1.3.4-py3.9-macosx-10.9-x86_64.egg/pandas/core/generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/Users/wxie/opt/miniconda3/lib/python3.9/site-packages/pandas-1.3.4-py3.9-macosx-10.9-x86_64.egg/pandas/core/generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/wxie/opt/miniconda3/lib/python3.9/site-packages/pandas-1.3.4-py3.9-macosx-10.9-x86_64.egg/pandas/core/indexes/base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['a'] not found in axis"
```

However, Pandas does support "label" as single parameter or list. The error is because in Pandas, both "index" and "column" axis are supported (and "index" axis can also be string-named) . And by default the `axis=0` makes it error (no "index" with name "a"). The following would work:

```python
>>> df.drop("a", axis=1)
   b
0  4
1  5
2  6
```

TorchArrow in general designed to not support complicated index-manipulation in most cases (index is always number, and we only support thing like `slice` and `append`). And column is the default operation. So there is no ambiguity to support `df.drop("a")`

**Comment by wenleix** [comment]
cc @dracifer

**Comment by Krish-bhardwaj** [comment]
Hi @wenleix  can you assign me this issue I can start working on it and if you can guide me on how to go about it that would be really helpful

**Comment by wenleix** [comment]
@Krish-bhardwaj : Thanks! I would start with 
https://github.com/pytorch/torcharrow/blob/5e464eacd0ed16a4bedf16d4aef7052af428f223/torcharrow/velox_rt/dataframe_cpu.py#L1860-L1874

and make it to also support `columns` as a single `str`.

You can add a test in (perhaps you need to have one more column otherwise everything will be dropped ;) ) https://github.com/pytorch/torcharrow/blob/5e464eacd0ed16a4bedf16d4aef7052af428f223/torcharrow/test/test_dataframe.py#L841-L842

**Comment by waitingkuo** [comment]
i just added a pull request for raise proper exception if we input a single str as columns
#419 

Looks like a contradiction with this issue?

**Comment by wenleix** [comment]
@waitingkuo Thanks for looking into this.

So they are related, but also reasonably separate issues: 
1.  `_check_columns` is a low-level check and its expectation (through type annotation) is to check a list of column names. So we can keep the behavior for now. We may want to revisit whether all of its usage can actually take a single string. (For now we decided `drop` wants to take a single string, but not sure about `groupby` and others)
2. For `drop`, we want it to support single string. One way is to wrap it into a list so it doesn't matter to `_check_columns` call, e.g. 
```python
 def drop(self, columns: Union[str, List[str]]): 
     if isinstance(columns, str):
         columns = [columns]
     self._check_columns(columns)
    ......
```

**Comment by waitingkuo** [comment]
@wenleix should we add it as a new function? i assume that we might have some other function need the same logic as well.

    def _wrap_columns_if_needed(self, columns: Union[str, List[str]]) -> List[str]:
        if isinstance(columns, str):
             columns = [columns]
        return columns

I'm not that good at naming though :(

**Comment by wenleix** [comment]
> @wenleix should we add it as a new function? i assume that we might have some other function need the same logic as well.

lol. Given the logic is quite simple, I would start with just inline them, and refactor later (depends on how these situations comes together, we may decide to fuse `check_column` and `wrap_single_column_list` , for example)

**Comment by waitingkuo** [comment]
added in #419

**Comment by wenleix** [comment]
Resolved by https://github.com/pytorch/torcharrow/pull/419
